### ISSUE TITLE
erbpp2.rb:152:in `def_method': wrong number of arguments (given 3, expected 1..2) 

### ISSUE THREAD

**Issue by dpblnt** [sonots/cumo#146]
/bin/mkdir -p narray/types types
ruby narray/gen/cogen.rb -l -o narray/types/scomplex.c narray/gen/def/scomplex.rb
/usr/local/lib64/ruby/gems/3.1.0/gems/cumo-0.4.3/ext/cumo/narray/gen/erbpp2.rb:152:in `def_method': wrong number of arguments (given 3, expected 1..2) (ArgumentError)
        from /usr/local/lib64/ruby/gems/3.1.0/gems/cumo-0.4.3/ext/cumo/narray/gen/narray_def.rb:30:in `set2'
        from spec.rb:219:in `block (2 levels) in <main>'
        from narray/gen/cogen.rb:51:in `eval'
        from narray/gen/cogen.rb:51:in `block (2 levels) in <main>'
        from /usr/local/lib64/ruby/gems/3.1.0/gems/cumo-0.4.3/ext/cumo/narray/gen/erbpp2.rb:12:in `instance_eval'
        from /usr/local/lib64/ruby/gems/3.1.0/gems/cumo-0.4.3/ext/cumo/narray/gen/erbpp2.rb:12:in `initialize'
        from /usr/local/lib64/ruby/gems/3.1.0/gems/cumo-0.4.3/ext/cumo/narray/gen/erbpp2.rb:179:in `initialize'
        from /usr/local/lib64/ruby/gems/3.1.0/gems/cumo-0.4.3/ext/cumo/narray/gen/erbpp2.rb:205:in `initialize'
        from /usr/local/lib64/ruby/gems/3.1.0/gems/cumo-0.4.3/ext/cumo/narray/gen/erbpp2.rb:138:in `new'
        from /usr/local/lib64/ruby/gems/3.1.0/gems/cumo-0.4.3/ext/cumo/narray/gen/erbpp2.rb:138:in `def_class'
        from narray/gen/cogen.rb:47:in `block in <main>'
        from /usr/local/lib64/ruby/gems/3.1.0/gems/cumo-0.4.3/ext/cumo/narray/gen/erbpp2.rb:12:in `instance_eval'
        from /usr/local/lib64/ruby/gems/3.1.0/gems/cumo-0.4.3/ext/cumo/narray/gen/erbpp2.rb:12:in `initialize'
        from /usr/local/lib64/ruby/gems/3.1.0/gems/cumo-0.4.3/ext/cumo/narray/gen/erbpp2.rb:125:in `initialize'
        from narray/gen/cogen.rb:37:in `new'
        from narray/gen/cogen.rb:37:in `<main>'
make: *** [Makefile:536: narray/types/scomplex.c] Error 1

make failed, exit code 2

**Comment by dpblnt** [comment]
With this patch I am able to build cumo, but I'm not sure if it is doing what it is supposed to
```
diff --git a/ext/cumo/narray/gen/narray_def.rb b/ext/cumo/narray/gen/narray_def.rb
index 5514018..03e804d 100644
--- a/ext/cumo/narray/gen/narray_def.rb
+++ b/ext/cumo/narray/gen/narray_def.rb
@@ -27,7 +27,7 @@ module NArrayMethod
 
   def set2(meth, dtype, result_class)
     h = {dtype:dtype, result_class:result_class}
-    def_method(meth, "set2", h)
+    def_method(meth, "set2", **h)
   end
 
   def cond_binary(meth,op=nil)
```
